name: dogstatsd-to-prom

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.122.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 8890:8890
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 8125:8125/udp # StatsD receiver
      - 8126:8126 # Datadog receiver over TCP

  statsd-exporter:
    image: prom/statsd-exporter:v0.26.1
    ports:
      - 9125:9125/udp # StatsD exporter port
      - 9102:9102 # Prometheus metrics port

