receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'karming-local'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8889']
  datadog:
    endpoint: "0.0.0.0:8126"
  statsd/local:
    endpoint: "0.0.0.0:8125"
    aggregation_interval: 10s  # default
    enable_metric_type: false # default

    # This is needed so that metrics aggregated with `delta` are processed by the Prometheus exporter.
    # A monotic `sum` is reported as an `counter` in Prometheus.
    # ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15353#issuecomment-1297858925
    # ref: https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#counters
    #
    # A `count` metrics by Dogstatsd is the total number of event occurences in one time interval.
    # ref: https://docs.datadoghq.com/metrics/types/?tab=count#metric-types
    # If it is always incrementing, then it is a 1:1 mapping to a Prometheus `counter`.
    is_monotonic_counter: true

connectors:
  spanmetrics:
    histogram:
        explicit:
          buckets: [10ms, 250ms, 500ms, 1s, 5s, 15s, 30s, 60s]
    aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"
    metrics_flush_interval: 60s

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  debug:
    verbosity: detailed

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    traces:
      receivers: [datadog]
      exporters: [spanmetrics]
    metrics:
      receivers: [otlp, statsd/local]
      exporters: [prometheus]
    metrics/prom:
      receivers: [prometheus]
      exporters: [debug]
  telemetry:
    logs:
      level: "warn"
