receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
  datadog:
    endpoint: "0.0.0.0:8126"

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
  telemetry:
    logs:
      level: "debug"
